/*
 * SimpleCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package io.apimatic.examples.controllers;

import io.apimatic.examples.Environment;
import io.apimatic.examples.SimpleCalculatorClient;
import io.apimatic.examples.testing.HttpCallbackCatcher;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.rules.Timeout;

/**
 * Base class for all test cases.
 */
public class BaseControllerTest {
    /**
     * Test configuration.
     */
    public static final int REQUEST_TIMEOUT = 30;

    public static final double ASSERT_PRECISION = 0.01;
    
    /**
     * Global rules for tests.
     */
    @Rule
    public Timeout globalTimeout = Timeout.seconds(REQUEST_TIMEOUT);
    
    /**
     * Test fixtures,
     * Used to serve as HttpCallback and to capture request & response.
     */

    protected static HttpCallbackCatcher httpResponse;
    
    /**
     * Setup test.
     */
    @BeforeClass
    public static void setUp() throws Exception {
        httpResponse = new HttpCallbackCatcher(); 
    }

    /**
     * Tear down test.
     */
    @AfterClass
    public static void tearDown() throws Exception {
        httpResponse = null;
    }

    /**
     * Create test configuration from Environment variables.
     */
    protected static SimpleCalculatorClient createConfigurationFromEnvironment() {
        SimpleCalculatorClient.Builder builder = new SimpleCalculatorClient.Builder();

        final String environment = System.getenv("SIMPLE_CALCULATOR_LIB_ENVIRONMENT");
        final String timeout = System.getenv("SIMPLE_CALCULATOR_LIB_TIMEOUT");
        final String username = System.getenv("SIMPLE_CALCULATOR_LIB_USERNAME");
        final String password = System.getenv("SIMPLE_CALCULATOR_LIB_PASSWORD");

        if (username != null && password != null) {
            builder.basicAuthCredentials(username, password);
        }
        if (environment != null) {
            builder.environment(Environment.fromString(environment));
        }
        if (timeout != null) {
            builder.httpClientConfig(configBuilder -> configBuilder.timeout(
                    Long.parseLong(timeout)));
        }
        return builder.build();
    }

    
    /**
     * Create test configuration.
     */
    protected static SimpleCalculatorClient createConfiguration() {
        // Set Configuration parameters for test execution
        SimpleCalculatorClient config = createConfigurationFromEnvironment();
        config = config.newBuilder()
                .httpCallback(httpResponse)
                .build();
        return config;
    }
}
