/*
 * SimpleCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package io.apimatic.examples.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import io.apimatic.examples.ApiHelper;
import io.apimatic.examples.SimpleCalculatorClient;
import io.apimatic.examples.exceptions.ApiException;
import io.apimatic.examples.models.OperationTypeEnum;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class SimpleCalculatorControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static SimpleCalculatorClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static SimpleCalculatorController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getSimpleCalculatorController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Test case for Calculate.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testSum() throws Exception {
        // Parameters for the API call
        OperationTypeEnum operation = OperationTypeEnum.fromString(
                "SUM");
        double x = 5d;
        double y = 6d;

        // Set callback and perform API call
        try {
            controller.calculate(operation, x, y);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
