/*
 * SimpleCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package io.apimatic.examples;

/**
 * Interface for defining the behavior of Basic Authentication.
 */
public interface BasicAuthCredentials {

    /**
     * String value for username.
     * @return username
     */
    String getUsername();

    /**
     * String value for password.
     * @return password
     */
    String getPassword();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param username String value for credentials.
     * @param password String value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String username, String password);
}