/*
 * SimpleCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package io.apimatic.examples;

import io.apimatic.examples.http.request.HttpRequest;
import java.util.Base64;
import java.util.concurrent.CompletableFuture;

/**
 * Utility class for authorization and token management.
 */
public class BasicAuthManager implements AuthManager, BasicAuthCredentials {

    private String username;

    private String password;

    /**
     * Constructor.
     * @param username String value for username.
     * @param password String value for password.
     */
    public BasicAuthManager(String username, String password) {
        this.username = username;
        this.password = password;
    }

    /**
     * String value for username.
     * @return username
     */
    public String getUsername() {
        return username;
    }

    /**
     * String value for password.
     * @return password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param username String value for credentials.
     * @param password String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String username, String password) {
        return username.equals(getUsername())
                && password.equals(getPassword());
    }

    /**
     * Converts this BasicAuthManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BasicAuthManager [" + "username=" + username + ", password=" + password + "]";
    }

    /**
     * Adds authentication to the given HttpRequest.
     */
    public HttpRequest apply(HttpRequest httpRequest) {
        String authCredentials = username + ":" + password;
        httpRequest.getHeaders().add("Authorization", "Basic " + Base64.getEncoder().encodeToString(authCredentials.getBytes()));
        return httpRequest;
    }

    /**
     * Asynchronously adds authentication to the given HttpRequest.
     */
    public CompletableFuture<HttpRequest> applyAsync(HttpRequest httpRequest) {
        String authCredentials = username + ":" + password;
        httpRequest.getHeaders().add("Authorization", "Basic " + Base64.getEncoder().encodeToString(authCredentials.getBytes()));
        return CompletableFuture.completedFuture(httpRequest);
    }
}
